FROM node:18.12.0-alpine AS node

WORKDIR /usr/src/app

COPY .env ./../
COPY ./client .

RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=node /usr/src/app/dist/client /usr/share/nginx/html