FROM node:18.12.0-alpine AS node

ARG DB_URI=http://localhost:8081

ENV NG_APP_DATABASE_URI=$DB_URI

WORKDIR /usr/src/app

COPY ./client .

RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=node /usr/src/app/dist/client /usr/share/nginx/html