version: '3.8'
services:
  angular-frontend:
    image: angular-frontend
    env_file: ./.env
    build:
      context: ./
      dockerfile: ./Dockerfile.client
    depends_on:
      - nestjs-backend
    ports:
      - '${DOCKER_CLIENT_PORT:-8080}:${NGINX_PORT:-80}'
    networks:
      - todo-app
    restart: unless-stopped

  nestjs-backend:
    image: nestjs-backend
    env_file: ./.env
    build:
      context: ./
      dockerfile: ./Dockerfile.server
    depends_on:
      - postgres-db
    ports:
      - '${DOCKER_SERVER_PORT:-8081}:${SERVER_PORT:-5000}'
    networks:
      - todo-app
    restart: unless-stopped

  postgres-db:
    image: postgres:15
    ports:
      - '${DOCKER_POSTGRES_PORT:-35000}:${POSTGRES_PORT:-5432}'
    env_file:
      - ./.env
    networks:
      - todo-app
    restart: unless-stopped

networks:
  todo-app:
    driver: bridge
